{
  name: "Mountain Gorilla",
  continent: "Africa",
  fun_fact: "Gorillas hate getting wet!",
  image: "https://ichef.bbci.co.uk/news/320/cpsprodpb/DF62/production/_101868175_hi018106787.jpg",
  conservation_status: "Endangered",
  number_remaining: 1000,
  locations: ["Uganda", "Rwanda"],
  quiz_question: "What kind of habitat do Mountain Gorillas live in?",
  correct_answer: "Cloud Forest",
  answers: ["Cloud Forest","Desert","Rainforest","Grassland"],
  answer_fact: "The forests the Mountain Gorillas live in are being cut down so that humans can build on the land. To protect the gorillas we need to make sure thay have enough suitable places to live",
  further_details: "https://www.wwf.org.uk/learn/wildlife/mountain-gorillas",
  threats: []
},
{
  name: "Giant Otter",
  continent: "South America",
  fun_fact: "Otters can close their ears and nose while underwater",
  image: "https://images.earthtouchnews.com/media/734835/9676405878_cff1361be4_o.jpg",
  conservation_status: "Endangered",
  number_remaining: 5000,
  locations: ["Suriname", "Guyana", "French Guiana"],
  quiz_question: "What type of food do otters mainly eat?",
  correct_answer: "Fish",
  answers: ["Fish","Insects","Plants","Snakes"],
  answer_fact: "Water pollution from mining is a serious danger to otters as it leads to an increase of mercury in their main diet of fish",
  further_details: "https://ptes.org/grants/worldwide-projects/giant-otters-peru/",
  threats: []
},
{
  name: "Javan Rhinoceros",
  continent: "Asia",
  fun_fact: "Rhinos like to wallow in mud, the activity allows them to maintain cool body temperatures and also helps prevent disease",
  image: "https://c402277.ssl.cf1.rackcdn.com/photos/9496/images/hero_full/_H9A0249.jpg?1436885827",
  conservation_status: "Critically Endangered",
  number_remaining: 67,
  locations: ["Indonesia"],
  quiz_question: "Can you guess where the Javan Rhinos live?",
  correct_answer: "Ujung Kulon National Park",
  answers: ["Ujung Kulon National Park","Cat Tien National Park","Bromo Tengger Semeru National Park","Komodo Island National Park"],
  answer_fact: "Javan rhinos are possibly the rarest large mammal on Earth. The only ones left live in the Ujung Kulon National Park, however the park is under threat from rising sea levels",
  further_details: "https://www.worldwildlife.org/species/javan-rhino",
  threats: []
},
{
  name: "Amur Leopard",
  continent: "Asia",
  fun_fact: "Amur Leopards have huge furry tails they can wrap around themselves to keep warm",
  image: "https://www.marwell.org.uk/media/images/full/amur_leopard_close_up_(1).jpg",
  conservation_status: "Critically Endangered",
  number_remaining: 90,
  locations: ["China", "Russia"],
  quiz_question: "Where do you think Amur Leopards like to live?",
  correct_answer: "Forests",
  answers: ["Forests","Mountains","Rivers","Deserts"],
  answer_fact: "The natural forest habitat of the Amur Leopards is being threatened by forest fires and by the construction of new roads.",
  further_details: "https://www.wwf.org.uk/learn/wildlife/amur-leopards",
  threats: []
},
{
  name: "African penguin",
  continent: "Africa",
  fun_fact: "They can hold their breath for up to 2 and a half minutes when diving",
  image: "https://upload.wikimedia.org/wikipedia/commons/6/63/African_penguin_side_profile.jpg",
  conservation_status: "Endangered",
  number_remaining: 21000,
  locations: ["South Africa","Namibia"],
  quiz_question: "African penguins are clumsy on land but excellent at swinning. How fast do you think they can swim?",
  correct_answer: "20 km per hour",
  answers: ["20 km per hour","5 km per hour","10 km per hour","30 km per hour"],
  answer_fact: "The African penguin population is declining rapidly, they suffer from pollution of their habitat by petrochemicals from spills, shipwrecks and cleaning of tankers while at sea",
  further_details: "https://www.britannica.com/animal/African-penguin",
  threats: []
},
{
  name: "Red Panda",
  continent: "Asia",
  fun_fact: "Red Pandas are only about 2 feet long, about the same size as a large domestic cat",
  image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Red_Panda_%2825193861686%29.jpg",
  conservation_status: "Endangered",
  number_remaining: 10000,
  locations: ["China", "Eastern Himalayas"],
  quiz_question: "What time of day are red pandas most active?",
  correct_answer: "At night",
  answers: ["At night","In the morning","In the afternoon","At lunchtime"],
  answer_fact: "The red panda population has declined by 50% over the last 20 years as deforestation removes their habitat.",
  further_details: "https://www.nationalgeographic.com/animals/mammals/r/red-panda/",
  threats: []
},
{
  name: "Hawksbill Sea Turtle",
  continent: "Oceans",
  fun_fact: "Hawksbill sea turtle shells change colors depending on whether the turtle is in warm or cold wate",
  image: "https://media.fromthegrapevine.com/assets/images/2015/2/hawksbill-sea-turtle-eilat-bay.jpg.1145x0_q71_crop-scale.jpg",
  conservation_status: "Critically Endangered",
  number_remaining: 23000,
  locations: ["Indian Ocean", "Pacific Ocean", "Atlantic Ocean"],
  quiz_question: "Hawksbill Turtles main diet is sea sponges and by eating them they help protect the coral reefs. How many sponges do you think a turtle can eat in a year?",
  correct_answer: "1200",
  answers: ["1200","20","500","2000"],
  answer_fact: "It is estimated that there are more than 100 million tonnes of plastic in the ocean, responsible for killing more than 100 million marine animals each year. It is believed that almost all sea turtles will ingest plastic in some form during their life.",
  further_details: "https://www.nationalgeographic.com/animals/reptiles/h/hawksbill-sea-turtle/",
  threats: []
},
{
  name: "Sumatran Elephant",
  continent: "Asia",
  fun_fact: "Despite a common opinion, elephants are not afraid of mice. Instead, they usually avoid ants and bees.",
  image: "https://onekindplanet.org/wp-content/uploads/2016/09/az-sumatran-elephant-small-wpcf_518x300.jpg",
  conservation_status: "Critically Endangered",
  number_remaining: 2600,
  locations: ["Indonesia"],
  quiz_question: "How many muscles are there in the trunk of a Sumatran elephant?",
  correct_answer: "60,000",
  answers: ["60,000","100","20,000","10,000"],
  answer_fact: "Due to conversion of forests into human settlements, agricultural areas and plantations, many of the Sumatran elephant populations have lost their habitat to humans.",
  further_details: "https://www.worldwildlife.org/species/sumatran-elephant",
  threats: ["deforestation", "poaching"]
},
{
  name: "African Wild Dog",
  continent: "Africa",
  fun_fact: "These long-legged canines have only four toes per foot, unlike other dogs, which have five toes on their forefeet.",
  image: "https://images.immediate.co.uk/production/volatile/sites/23/2019/11/P6071681-de6c1f1.jpg?webp=true&quality=45&resize=1240%2C826",
  conservation_status: "Endangered",
  number_remaining: 6000,
  locations: ["Botswana", "Namibia", "Zimbabwe"],
  quiz_question: "What is another name for the African Wild Dog",
  correct_answer: "Painted Wolf",
  answers: ["Painted Wolf","Stripey Wolf","Fierce Wolf","Short Haired Wolf"],
  answer_fact: "The biggest threat to wild dogs is destruction of their habitat, as human populations expand, wild dogs are losing the spaces in which they were once able to roam freely. However organisations are working to create protected areas for these species so they have somewhere to live",
  further_details: "https://www.awf.org/wildlife-conservation/african-wild-dog",
  threats: ["disease", "farming", "climate change"]
},
{
  name: "Emperor penguin",
  continent: "Antarctica",
  fun_fact: "Emporer penguins are the largest penguins on earth today, but they would be dwarfed by the ancient ‘mega-penguins’. Fossils reveal that a giant species of penguin which lived about 37 million years ago may have stood 2 metres tall!",
  image: "https://oceanwide-4579.kxcdn.com/uploads/media-dynamic/cache/widen_1100/uploads/media/default/0001/26/thumb_25671_default_900.jpeg",
  conservation_status: "Near Threatened",
  number_remaining: 595000,
  locations: ["Antarctica"],
  quiz_question: "Emperor penguins are the Olympic divers of the bird world! How deep do you think the deepest recorded penguin dive is?",
  correct_answer: "564 metres",
  answers: ["564 metres", "50 metres", "100 metres", "1000 metres"],
  answer_fact: "Emperor Penguins are at risk from global warming, which is melting the sea ice. However if climate targets can be met the risk to these penguins will be greatly reduced.",
  further_details: "https://www.natgeokids.com/uk/discover/animals/birds/emperor-penguins/",
  threats: ["climate change"]
},
{
  name: "Antarctic Blue Whale",
  continent: "Antarctica",
  fun_fact: "Blue whales are the largest mammal to have ever lived on the Earth, but their main diet is tiny krill, a small aquatic lifeform resembling a prawn",
  image: "https://cdn.britannica.com/90/150290-050-C96E4444/Illustration-blue-whale.jpg",
  conservation_status: "Endangered",
  number_remaining: 25000,
  locations: ["Southern Ocean"],
  quiz_question: "Which of these facts about the Blue Whale is NOT true?",
  correct_answer: "It can swim at 40 miles per hour",
  answers: ["It can swim at 40 miles per hour","It's calls can be heard underwater for hundreds of kilometres","It’s tongue weighs as much as an elephant","It is longer than three buses"],
  answer_fact: "The world's largest problem, global warming, could mean extinction in the Antarctic for the world's largest animal. Sea ice provides a habitat for algae, which are fed upon by krill, the main food supply for blue whales. As the temperature has increased in recent decades, sea ice has diminished rapidly and thus food supplies for krill are getting scarce.",
  further_details: "https://wwf.panda.org/knowledge_hub/endangered_species/cetaceans/about/blue_whale/",
  threats: ["poaching", "climate change", "fishing"]
},
{
  name: "Antarctic Krill",
  continent: "Antarctica",
  fun_fact: "Krill travel in swarms so dense they can be seen from space.",
  image: "http://www.antarctica.gov.au/__data/assets/image/0010/29098/varieties/antarctic.jpg",
  conservation_status: "Least Concern",
  number_remaining: 6000000000,
  locations: ["Southern Oceans"],
  quiz_question: "How big can krill grow",
  correct_answer: "6cm",
  answers: ["6cm","2cm","10cm","20cm"],
  answer_fact: "Although krill are not currently endangered their numbers are declining, as global warming causes the ice caps which provide their food to melt. Without krill to eat, the majority of life forms in the Antarctic would vanish",
  further_details: "https://www.nationalgeographic.com/animals/invertebrates/group/krill/",
  threats: ["climate change"]
},
